### PR TITLE
fix: cast overflow in 32-bits OS

### LINKED ISSUE #971: Bug report: Due to incorrect use of implicit conversion(`as`), some cases do not work in 32-bit operating systems.
# Root cause

I found `revm` used the implicit conversion `as` without checking the overflow, like: 

https://github.com/bluealloy/revm/blob/23cbac479f616eba5ab11ddfe6d5814b9c492202/crates/interpreter/src/instructions/macros.rs#L216

https://github.com/bluealloy/revm/blob/23cbac479f616eba5ab11ddfe6d5814b9c492202/crates/interpreter/src/instructions/macros.rs#L201
and so on.

In `revm` we usually convert `u64` to `usize`. Therefore, it's perfectly fine when running on a 64-bit OS. However, in a 32-bit OS, the rules are different, and it will silently overflow and return **unsound values**.

# Case study;TLDR

Failed case from `zeth`: https://github.com/risc0/zeth/issues/52

## What happened?

When you track the traces of the `revm` execution, you will find:
```diff
depth:1, PC:0, gas:0x9ffffadf8(42949651960), OPCODE: "PUSH15"(110)  refund:0x0(0) Stack:[], Data size:0
depth:1, PC:16, gas:0x9ffffadf5(42949651957), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000112233445566778899aabbccddeeff_U256], Data size:0
depth:1, PC:18, gas:0x9ffffadf2(42949651954), OPCODE: "MSTORE"(82)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000112233445566778899aabbccddeeff_U256, 0x0_U256], Data size:0
depth:1, PC:19, gas:0x9ffffadec(42949651948), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[], Data size:32
depth:1, PC:21, gas:0x9ffffade9(42949651945), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[0x000000000000000000000000000000000000000000000000000000000000003f_U256], Data size:32
depth:1, PC:23, gas:0x9ffffade6(42949651942), OPCODE: "EXP"(10)  refund:0x0(0) Stack:[0x000000000000000000000000000000000000000000000000000000000000003f_U256, 0x0000000000000000000000000000000000000000000000000000000000000002_U256], Data size:32
depth:1, PC:24, gas:0x9ffffadaa(42949651882), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000000000000000008000000000000000_U256], Data size:32
depth:1, PC:26, gas:0x9ffffada7(42949651879), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000000000000000008000000000000000_U256, 0x000000000000000000000000000000000000000000000000000000000000003f_U256], Data size:32
depth:1, PC:28, gas:0x9ffffada4(42949651876), OPCODE: "EXP"(10)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000000000000000008000000000000000_U256, 0x000000000000000000000000000000000000000000000000000000000000003f_U256, 0x0000000000000000000000000000000000000000000000000000000000000002_U256], Data size:32
depth:1, PC:29, gas:0x9ffffad68(42949651816), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000000000000000008000000000000000_U256, 0x0000000000000000000000000000000000000000000000008000000000000000_U256], Data size:32
depth:1, PC:31, gas:0x9ffffad65(42949651813), OPCODE: "RETURNDATACOPY"(62)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000000000000000008000000000000000_U256, 0x0000000000000000000000000000000000000000000000008000000000000000_U256, 0x0_U256], Data size:32
+ depth:1, PC:32, gas:0x9ffffad62(42949651810), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:[], Data size:32
+ depth:1, PC:34, gas:0x9ffffad5f(42949651807), OPCODE: "MLOAD"(81)  refund:0x0(0) Stack:[0x0_U256], Data size:32
+ depth:1, PC:35, gas:0x9ffffad5c(42949651804), OPCODE: "PUSH1"(96)  refund:0x0(0) Stack:-[0x0000000000000000000000000000000000112233445566778899aabbccddeeff_U256], Data size:32
+ depth:1, PC:37, gas:0x9ffffad59(42949651801), OPCODE: "SSTORE"(85)  refund:0x0(0) Stack:[0x0000000000000000000000000000000000112233445566778899aabbccddeeff_U256, 0x0_U256], Data size:32
```
The binary running in the risc0-vm has over 4 traces, but it will terminate and return `OutOfGas` when reaching the `RETURNDATACOPY` opcode if run outside of it. Both of them have the same program, but what the difference between them? 
The `RETURNDATACOPY` has 3 parameters[^1]:
|Parameter|Value|
|----------|------|
| destOffset | 0x0|
| offset | 0x0000000000000000000000000000000000000000000000008000000000000000 |
| size | 0x0000000000000000000000000000000000000000000000008000000000000000 |

The gas cost of this opcode will be `864691128455135253`, which is far greater than the gas limit.
We discovered that the subsequent `PUSH1` opcode has 42949651810 remaining gas, whereas the previous one had 42949651813, indicating a cost of only three gases. This is equivalent to the static gas of `RETURNDATACOPY`. Therefore, the total gas was not calculated using the `size` value (dynamic gas was missing).

https://github.com/bluealloy/revm/blob/23cbac479f616eba5ab11ddfe6d5814b9c492202/crates/interpreter/src/instructions/system.rs#L111-L130

The only reason here is that `gas::verylowcopy_cost(len as u64)` returns 3, which should not be. Unless there are some issues with the `risc0-vm` or `riscv32im-risc0-zkvm-elf` target. However, no matter how the code is modified, this bug can be reproduced stably and can largely eliminate some UBs.
https://github.com/bluealloy/revm/blob/23cbac479f616eba5ab11ddfe6d5814b9c492202/crates/interpreter/src/gas/calc.rs#L107-L111
So, I found the line get `len` return 0.

https://github.com/bluealloy/revm/blob/23cbac479f616eba5ab11ddfe6d5814b9c492202/crates/interpreter/src/instructions/system.rs#L114

https://github.com/bluealloy/revm/blob/23cbac479f616eba5ab11ddfe6d5814b9c492202/crates/interpreter/src/instructions/macros.rs#L205-L218

Since the value of `len` is `9223372036854776000`, which exceeds `usize::MAX` in a 32-bit OS, an overflow occurred and returned a value of 0.

# How to fix?
We cannot resolve this issue without making significant modifications to the codebase. Because `revm` used lots of `usize`, like the index&offset of `Memory`, all opcodes that use the `len` and so on.

## Approach 1
I think a good way is to align with the implementation of `geth`[^2], all of these places, we use the `u64` instead of `usize`, like use a `u64` indexed `Memory`.

https://github.com/ethereum/go-ethereum/blob/master/core/vm/memory.go#L35

## Approach 2
Let it fail fast, only return an error in cases of casting overflow, such as `CastOVerflow`.
To prevent developers from using the `as` keyword for casting, we can add a `#![warn(clippy::cast_lossless)]` compile attribute to perform a Clippy lint check[^3].
And it should be:

```rust
usize::try_from(x[0]).map_error(|_|CastOverflow)
```

However, this will cause inconsistent behavior between 32-bit and 64-bit operating systems.

# Conclusion
**In any case, it is crucial to avoid using `as`.**

[^1]: https://www.evm.codes/#3e?fork=shanghai
[^2]: https://github.com/ethereum/go-ethereum
[^3]: https://rust-lang.github.io/rust-clippy/master/#/cast_lossless

### PR DESCRIPTION
**Pull request by dyxushuai**
Close #971

+r @rakita

### CODE REVIEW

File: crates/interpreter/src/instructions/macros.rs [hunk 1]
```diff
@@ -205,6 +211,12 @@ macro_rules! as_usize_or_fail {
...
             return;
         }
-        x[0] as usize
+        match ::core::convert::TryInto::<usize>::try_into(x[0]) {
+            Ok(val) => val,
+            Err(_) => {
+                $interp.instruction_result = $reason;
+                return;
+            }
+        }
```
Comment (rakita) [inline crates/interpreter/src/instructions/macros.rs:220]:
```suggestion
        let Ok(val) = match ::core::convert::TryInto::<usize>::try_into(x[0])  else {
                $interp.instruction_result = $reason;
                return;
        }
        val
```

We can use `let else` here

File: crates/interpreter/src/instructions/macros.rs [hunk 2]
```diff
@@ -189,8 +189,14 @@ macro_rules! as_u64_saturated {
...
-    ($v:expr) => {
-        as_u64_saturated!($v) as usize
+    ($interp:expr, $v:expr) => {
+        match ::core::convert::TryInto::<usize>::try_into(as_u64_saturated!($v)) {
+            Ok(val) => val,
+            Err(_) => {
+                $interp.instruction_result = InstructionResult::InvalidOperandOOG;
+                return;
+            }
+        }
```
Comment (rakita) [inline crates/interpreter/src/instructions/macros.rs:199]: We should return saturated usize here, it is a consensus error if we fail here.

```suggestion
        ::core::convert::TryInto::<usize>::try_into(as_u64_saturated!($v)).unwrap_or(usize::MAX)
```

**Comment by Wollac** [comment]
I haven't run the zeth tests with it yet, but it seems that the eth tests still fail for me on `i686-unknown-linux-gnu`. Of course, this could be unrelated.

```
Running tests in tests/GeneralStateTests/...

Traces:

Execution result: Ok(
    Halt {
        reason: OutOfGas(
            InvalidOperand,
        ),
        gas_used: 4000000,
    },
)

Expected exception: None

State before: CacheState {
    accounts: {
        0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b: CacheAccount {
            account: Some(
                PlainAccount {
                    info: AccountInfo {
                        balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
                        nonce: 0,
                        code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470,
                        code: Some(
                            Bytecode {
                                bytecode: 0x,
                                state: Raw,
                            },
                        ),
                    },
                    storage: {},
                },
            ),
            status: Loaded,
        },
        0x095e7baea6a6c7c4c2dfeb977efac326af552d87: CacheAccount {
            account: Some(
                PlainAccount {
                    info: AccountInfo {
                        balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
                        nonce: 0,
                        code_hash: 0x003dee9cac09c55c8fd75f8345bd106bb755d5c2a2f3f57d544a02723cfa8934,
                        code: Some(
                            Bytecode {
                                bytecode: 0x600049600055600a4960015563ffffffff4960025567ffffffffffffffff496003556fffffffffffffffffffffffffffffffff496004557fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4960055500,
                                state: Raw,
                            },
                        ),
                    },
                    storage: {
                        0x0000000000000000000000000000000000000000000000000000000000000001_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000004_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000005_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000003_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000002_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                    },
                },
            ),
            status: Loaded,
        },
    },
    contracts: {},
    has_state_clear: false,
}

State after: CacheState {
    accounts: {
        0x0000000000000000000000000000000000000000: CacheAccount {
            account: Some(
                PlainAccount {
                    info: AccountInfo {
                        balance: 0x0_U256,
                        nonce: 1,
                        code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470,
                        code: Some(
                            Bytecode {
                                bytecode: 0x00,
                                state: Analysed {
                                    len: 0,
                                    jump_map: JumpMap {
                                        map: "00",
                                    },
                                },
                            },
                        ),
                    },
                    storage: {},
                },
            ),
            status: InMemoryChange,
        },
        0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b: CacheAccount {
            account: Some(
                PlainAccount {
                    info: AccountInfo {
                        balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
                        nonce: 0,
                        code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470,
                        code: Some(
                            Bytecode {
                                bytecode: 0x,
                                state: Raw,
                            },
                        ),
                    },
                    storage: {},
                },
            ),
            status: Loaded,
        },
        0x095e7baea6a6c7c4c2dfeb977efac326af552d87: CacheAccount {
            account: Some(
                PlainAccount {
                    info: AccountInfo {
                        balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
                        nonce: 0,
                        code_hash: 0x003dee9cac09c55c8fd75f8345bd106bb755d5c2a2f3f57d544a02723cfa8934,
                        code: Some(
                            Bytecode {
                                bytecode: 0x600049600055600a4960015563ffffffff4960025567ffffffffffffffff496003556fffffffffffffffffffffffffffffffff496004557fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4960055500,
                                state: Raw,
                            },
                        ),
                    },
                    storage: {
                        0x0000000000000000000000000000000000000000000000000000000000000001_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000004_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000005_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000003_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                        0x0000000000000000000000000000000000000000000000000000000000000002_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                    },
                },
            ),
            status: Loaded,
        },
    },
    contracts: {},
    has_state_clear: true,
}

Specification: CANCUN

Environment: Env {
    cfg: CfgEnv {
        chain_id: 1,
        kzg_settings: Default,
        perf_analyse_created_bytecodes: Analyse,
        limit_contract_code_size: None,
    },
    block: BlockEnv {
        number: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
        coinbase: 0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba,
        timestamp: 0x00000000000000000000000000000000000000000000000000000000000003e8_U256,
        gas_limit: 0x0000000000000000000000000000000000000000000000000000001000000000_U256,
        basefee: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
        difficulty: 0x0000000000000000000000000000000000000000000000000000000000020000_U256,
        prevrandao: Some(
            0x0000000000000000000000000000000000000000000000000000000000020000,
        ),
        blob_excess_gas_and_price: Some(
            BlobExcessGasAndPrice {
                excess_blob_gas: 0,
                blob_gasprice: 1,
            },
        ),
    },
    tx: TxEnv {
        caller: 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b,
        gas_limit: 4000000,
        gas_price: 0x000000000000000000000000000000000000000000000000000000012a05f200_U256,
        transact_to: Call(
            0x095e7baea6a6c7c4c2dfeb977efac326af552d87,
        ),
        value: 0x00000000000000000000000000000000000000000000000000000000000186a0_U256,
        data: 0x00,
        nonce: None,
        chain_id: None,
        access_list: [
            (
                0x095e7baea6a6c7c4c2dfeb977efac326af552d87,
                [
                    0x0_U256,
                    0x0000000000000000000000000000000000000000000000000000000000000001_U256,
                ],
            ),
        ],
        gas_priority_fee: Some(
            0x0000000000000000000000000000000000000000000000000000000000000002_U256,
        ),
        blob_hashes: [
            0x01a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8,
            0x01a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8,
        ],
        max_fee_per_blob_gas: Some(
            0x000000000000000000000000000000000000000000000000000000000000000a_U256,
        ),
    },
}

Test name: "opcodeBlobhBounds" (index: 0, path: tests/GeneralStateTests/Cancun/stEIP4844-blobtransactions/opcodeBlobhBounds.json) failed:
Test opcodeBlobhBounds failed: state root mismatch: expected 0x426146b44c5917613224a944ceff7c3672f26f7a9bee97f7c8b9b097d67cb3a9, got 0x2c526db07cff1c6794440d3258ae3890c2e1faa3ba619540b94b4316230c73fe
```

File: crates/interpreter/src/instructions/macros.rs (hunk 2 above)
Comment (rakita) [reply crates/interpreter/src/instructions/macros.rs:199]: @Wollac this can be a reason for test failure.

File: crates/interpreter/src/instructions/macros.rs (hunk 1 above)
Comment (dyxushuai) [reply crates/interpreter/src/instructions/macros.rs:220]: `let else` needs a newer version of rust (>=1.65), that means we need to give up the old users. Does it make sense?
https://doc.rust-lang.org/rust-by-example/flow_control/let_else.html

**Comment by dyxushuai** [comment]
> I haven't run the zeth tests with it yet, but it seems that the eth tests still fail for me on `i686-unknown-linux-gnu`. Of course, this could be unrelated.
> 
> ```
> Running tests in tests/GeneralStateTests/...
> 
> Traces:
> 
> Execution result: Ok(
>     Halt {
>         reason: OutOfGas(
>             InvalidOperand,
>         ),
>         gas_used: 4000000,
>     },
> )
> 
> Expected exception: None
> 
> State before: CacheState {
>     accounts: {
>         0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b: CacheAccount {
>             account: Some(
>                 PlainAccount {
>                     info: AccountInfo {
>                         balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
>                         nonce: 0,
>                         code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470,
>                         code: Some(
>                             Bytecode {
>                                 bytecode: 0x,
>                                 state: Raw,
>                             },
>                         ),
>                     },
>                     storage: {},
>                 },
>             ),
>             status: Loaded,
>         },
>         0x095e7baea6a6c7c4c2dfeb977efac326af552d87: CacheAccount {
>             account: Some(
>                 PlainAccount {
>                     info: AccountInfo {
>                         balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
>                         nonce: 0,
>                         code_hash: 0x003dee9cac09c55c8fd75f8345bd106bb755d5c2a2f3f57d544a02723cfa8934,
>                         code: Some(
>                             Bytecode {
>                                 bytecode: 0x600049600055600a4960015563ffffffff4960025567ffffffffffffffff496003556fffffffffffffffffffffffffffffffff496004557fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4960055500,
>                                 state: Raw,
>                             },
>                         ),
>                     },
>                     storage: {
>                         0x0000000000000000000000000000000000000000000000000000000000000001_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000004_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000005_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000003_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000002_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                     },
>                 },
>             ),
>             status: Loaded,
>         },
>     },
>     contracts: {},
>     has_state_clear: false,
> }
> 
> State after: CacheState {
>     accounts: {
>         0x0000000000000000000000000000000000000000: CacheAccount {
>             account: Some(
>                 PlainAccount {
>                     info: AccountInfo {
>                         balance: 0x0_U256,
>                         nonce: 1,
>                         code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470,
>                         code: Some(
>                             Bytecode {
>                                 bytecode: 0x00,
>                                 state: Analysed {
>                                     len: 0,
>                                     jump_map: JumpMap {
>                                         map: "00",
>                                     },
>                                 },
>                             },
>                         ),
>                     },
>                     storage: {},
>                 },
>             ),
>             status: InMemoryChange,
>         },
>         0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b: CacheAccount {
>             account: Some(
>                 PlainAccount {
>                     info: AccountInfo {
>                         balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
>                         nonce: 0,
>                         code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470,
>                         code: Some(
>                             Bytecode {
>                                 bytecode: 0x,
>                                 state: Raw,
>                             },
>                         ),
>                     },
>                     storage: {},
>                 },
>             ),
>             status: Loaded,
>         },
>         0x095e7baea6a6c7c4c2dfeb977efac326af552d87: CacheAccount {
>             account: Some(
>                 PlainAccount {
>                     info: AccountInfo {
>                         balance: 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000_U256,
>                         nonce: 0,
>                         code_hash: 0x003dee9cac09c55c8fd75f8345bd106bb755d5c2a2f3f57d544a02723cfa8934,
>                         code: Some(
>                             Bytecode {
>                                 bytecode: 0x600049600055600a4960015563ffffffff4960025567ffffffffffffffff496003556fffffffffffffffffffffffffffffffff496004557fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4960055500,
>                                 state: Raw,
>                             },
>                         ),
>                     },
>                     storage: {
>                         0x0000000000000000000000000000000000000000000000000000000000000001_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000004_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000005_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000003_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                         0x0000000000000000000000000000000000000000000000000000000000000002_U256: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                     },
>                 },
>             ),
>             status: Loaded,
>         },
>     },
>     contracts: {},
>     has_state_clear: true,
> }
> 
> Specification: CANCUN
> 
> Environment: Env {
>     cfg: CfgEnv {
>         chain_id: 1,
>         kzg_settings: Default,
>         perf_analyse_created_bytecodes: Analyse,
>         limit_contract_code_size: None,
>     },
>     block: BlockEnv {
>         number: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>         coinbase: 0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba,
>         timestamp: 0x00000000000000000000000000000000000000000000000000000000000003e8_U256,
>         gas_limit: 0x0000000000000000000000000000000000000000000000000000001000000000_U256,
>         basefee: 0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>         difficulty: 0x0000000000000000000000000000000000000000000000000000000000020000_U256,
>         prevrandao: Some(
>             0x0000000000000000000000000000000000000000000000000000000000020000,
>         ),
>         blob_excess_gas_and_price: Some(
>             BlobExcessGasAndPrice {
>                 excess_blob_gas: 0,
>                 blob_gasprice: 1,
>             },
>         ),
>     },
>     tx: TxEnv {
>         caller: 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b,
>         gas_limit: 4000000,
>         gas_price: 0x000000000000000000000000000000000000000000000000000000012a05f200_U256,
>         transact_to: Call(
>             0x095e7baea6a6c7c4c2dfeb977efac326af552d87,
>         ),
>         value: 0x00000000000000000000000000000000000000000000000000000000000186a0_U256,
>         data: 0x00,
>         nonce: None,
>         chain_id: None,
>         access_list: [
>             (
>                 0x095e7baea6a6c7c4c2dfeb977efac326af552d87,
>                 [
>                     0x0_U256,
>                     0x0000000000000000000000000000000000000000000000000000000000000001_U256,
>                 ],
>             ),
>         ],
>         gas_priority_fee: Some(
>             0x0000000000000000000000000000000000000000000000000000000000000002_U256,
>         ),
>         blob_hashes: [
>             0x01a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8,
>             0x01a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8,
>         ],
>         max_fee_per_blob_gas: Some(
>             0x000000000000000000000000000000000000000000000000000000000000000a_U256,
>         ),
>     },
> }
> 
> Test name: "opcodeBlobhBounds" (index: 0, path: tests/GeneralStateTests/Cancun/stEIP4844-blobtransactions/opcodeBlobhBounds.json) failed:
> Test opcodeBlobhBounds failed: state root mismatch: expected 0x426146b44c5917613224a944ceff7c3672f26f7a9bee97f7c8b9b097d67cb3a9, got 0x2c526db07cff1c6794440d3258ae3890c2e1faa3ba619540b94b4316230c73fe
> ```

Sorry, I didn't test the failed issues. I will test it and make sure it works.

File: crates/interpreter/src/instructions/macros.rs (hunk 2 above)
Comment (dyxushuai) [reply crates/interpreter/src/instructions/macros.rs]: > @Wollac this can be a reason for test failure.

I think so, I misunderstood of this macro.

**Comment by Wollac** [comment]
I can now confirm that `i686-unknown-linux-gnu` as well as the [zeth issue](https://github.com/risc0/zeth/issues/52) seems to be fixed for me.
However, shouldn't it also be possible to run the (eth) tests on the CI on i686-unknown-linux-gnu? I think that might be something worth adding to prevent problems like this in the future.

**Comment by dyxushuai** [comment]
> I can now confirm that `i686-unknown-linux-gnu` as well as the [zeth issue](https://github.com/risc0/zeth/issues/52) seems to be fixed for me. However, shouldn't it also be possible to run the (eth) tests on the CI on i686-unknown-linux-gnu? I think that might be something worth adding to prevent problems like this in the future.

@Wollac @rakita Sounds good, I can try to add it

**Review by rakita — APPROVED** [review]
This lgtm!

Will wait for CI before merging, let me know if you need help

**Comment by dyxushuai** [comment]
@rakita It's ready for review and merging.

**Review by rakita — APPROVED** [review]
TIL about cross
