### PR TITLE
fix: replace tuple in sstore return with struct

### LINKED ISSUE #1114: Replace tuple in sstore return with struct
https://github.com/bluealloy/revm/blob/main/crates/revm/src/journaled_state.rs#L655
Replace this output with a struct that defines the names of variables

### PR DESCRIPTION
**Pull request by qiweiii**
fix #1114

### CODE REVIEW

File: crates/interpreter/src/host.rs [hunk 1]
```diff
@@ -56,3 +51,13 @@ pub trait Host {
     /// Mark `address` to be deleted, with funds transferred to `target`.
     fn selfdestruct(&mut self, address: Address, target: Address) -> Option<SelfDestructResult>;
 }
+
+/// Represents the result of an `sstore` operation.
+#[derive(Debug, Clone, PartialEq, Eq)]
+#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
+pub struct SStoreResult {
```
Comment (qiweiii) [inline crates/interpreter/src/host.rs:58]: not sure if this is the right file to place it

Comment (rakita) [reply crates/interpreter/src/host.rs:58]: The place is fine, would add more comments.

original: `Value of the storage when it is first read`
present: `Current value of the storage`
new_value: `Values that that is set`
is_cold: `Is storage slot loaded from database`

**Review by rakita — APPROVED** [review]
nit on comments otherwise lgtm

File: crates/interpreter/src/host.rs (hunk 1 above)
Comment (qiweiii) [reply crates/interpreter/src/host.rs:58]: updated!

**Comment by rakita** [comment]
Clippy not related

File: crates/interpreter/src/host.rs [hunk 2]
```diff
@@ -56,3 +51,17 @@ pub trait Host {
...
+    /// Value of the storage when it is first read
+    pub original_value: U256,
+    /// Current value of the storage
+    pub present_value: U256,
+    /// Values that that is set
```
Comment (rakita) [inline crates/interpreter/src/host.rs:63]:
```suggestion
    /// New value that is set
```
